#!/bin/bash

echo "🚀 eCommerce API - Postman Collection Generator"
echo "=============================================="

# Configuration
API_URL="http://localhost:3151"
HEALTH_ENDPOINT="/health"
OPENAPI_ENDPOINT="/api-json"
POSTMAN_DIR="postman"
COLLECTION_FILE="generated-postman-collection.json"
ENVIRONMENT_FILE="postman-environment.json"

# Create postman directory if it doesn't exist
if [ ! -d "$POSTMAN_DIR" ]; then
    echo "📁 Creating postman directory..."
    mkdir -p "$POSTMAN_DIR"
    echo "✅ Directory created: $POSTMAN_DIR/"
fi

# Check if API is running
echo "📡 Checking if API is running at $API_URL..."
if ! curl -sf "$API_URL$HEALTH_ENDPOINT" > /dev/null; then
    echo "❌ Error: API is not running at $API_URL"
    echo "   Please start the API server with: npm run start:dev"
    exit 1
fi

echo "✅ API is running successfully!"

# Download OpenAPI specification
echo "� Downloading OpenAPI specification..."
if ! curl -sf "$API_URL$OPENAPI_ENDPOINT" -o "postman-collection-openapi.json"; then
    echo "❌ Error: Could not download OpenAPI specification"
    echo "   Make sure the API is running and OpenAPI documentation is available"
    exit 1
fi

echo "✅ OpenAPI specification downloaded!"

echo ""
echo "📋 Available Postman Collections:"
echo "================================="
echo "1. 📁 $POSTMAN_DIR/postman-collection-openapi.json - Traditional OpenAPI-generated collection (no tests)"
echo "2. 📁 $POSTMAN_DIR/postman-collection.json - Complete API test suite (32 requests, ~100+ tests)"
echo "3. 📁 $POSTMAN_DIR/postman-collection-practice.json - Practice test suite (empty tests for learning)"
echo "4. 📁 $POSTMAN_DIR/postman-environment.json - Environment variables and test data"
echo ""

# Run the collections if requested
echo "🔧 Usage Options:"
echo "================"
echo ""
echo "Option 1: Import into Postman GUI"
echo "  📋 For basic API exploration (no tests):"
echo "    • Import '$POSTMAN_DIR/postman-collection-openapi.json' directly"
echo "    • Import '$POSTMAN_DIR/postman-environment.json' for variables"
echo ""
echo "  🧪 For comprehensive testing:"
echo "    • Import '$POSTMAN_DIR/postman-collection.json' and '$POSTMAN_DIR/postman-environment.json'"
echo "    • Use Collection Runner to execute all tests"
echo ""
echo "  📚 For learning/practice:"
echo "    • Import '$POSTMAN_DIR/postman-collection-practice.json' and '$POSTMAN_DIR/postman-environment.json'"
echo "    • Fill in TODO sections to learn API testing"
echo ""
echo "Option 2: Run with Newman CLI"
echo "  🏃‍♂️ For automated testing in CI/CD: Not in scope"
echo ""

# Offer to run tests
echo "🚀 Collection Import Instructions:"
echo "=================================="
echo ""
echo "📋 To import the traditional OpenAPI collection (basic endpoints):"
echo "   1. Open Postman"
echo "   2. Click 'Import' → 'Upload Files'"
echo "   3. Navigate to '$POSTMAN_DIR/' folder"
echo "   4. Select 'openapi-spec.json'"
echo "   5. Also import 'postman-environment.json' for environment variables"
echo "   6. This gives you all endpoints for manual testing"
echo ""
echo "🧪 To import the comprehensive test collection:"
echo "   1. Import both '$POSTMAN_DIR/postman-collection.json' and '$POSTMAN_DIR/postman-environment.json'"
echo "   2. Use Collection Runner to execute automated tests"
echo ""
echo "📚 To import the practice collection for learning:"
echo "   1. Import both '$POSTMAN_DIR/postman-collection-practice.json' and '$POSTMAN_DIR/postman-environment.json'"
echo "   2. Fill in TODO sections in test scripts to learn API testing"
echo ""
echo "🔗 Direct OpenAPI import (alternative):"
echo "   • In Postman: Import → Link → http://localhost:3151/api-json"
echo ""

echo ""
echo "📊 Test Coverage Summary:"
echo "========================="
echo "• Authentication & Security: ✅ JWT, login/logout, role-based access"
echo "• User Management: ✅ CRUD operations, search, validation"  
echo "• Product Management: ✅ Admin operations, public access, filtering"
echo "• Order Processing: ✅ Creation, status updates, history"
echo "• Review System: ✅ CRUD operations, product association"
echo "• Authorization: ✅ Role-based permissions, security testing"
echo "• Error Handling: ✅ Validation, 404s, unauthorized access"
echo "• Health Checks: ✅ API availability, performance"
echo "• E2E Workflows: ✅ Complete customer journeys, edge cases"
echo ""
echo "📁 Generated Files:"
echo "=================="
echo "• $POSTMAN_DIR/postman-collection-openapi.json - OpenAPI specification & traditional Postman collection"
echo "• $POSTMAN_DIR/postman-collection.json - Comprehensive test collection"
echo "• $POSTMAN_DIR/postman-collection-practice.json - Practice test collection with TODO sections"
echo "• $POSTMAN_DIR/postman-environment.json - Environment variables"
echo "• $POSTMAN_DIR/test-report.html - Test execution report (if tests ran)"
echo ""
echo "🎯 Next Steps:"
echo "=============="
echo "1. Import $POSTMAN_DIR/postman-collection-openapi.json for basic API exploration"
echo "2. Import $POSTMAN_DIR/postman-collection.json for comprehensive testing"
echo "3. Import $POSTMAN_DIR/postman-collection-practice.json for learning API testing"
echo ""
echo "💡 Collection Types Explained:"
echo "============================="
echo "🔧 $POSTMAN_DIR/postman-collection-openapi.json:"
echo "   • Basic endpoints without test scripts"
echo "   • Good for API exploration and manual testing"
echo "   • Generated directly from OpenAPI specification"
echo ""
echo "🧪 $POSTMAN_DIR/postman-collection.json:"
echo "   • Comprehensive test suite with assertions"
echo "   • Automated validation of responses"
echo "   • Equivalent to your Jest integration tests"
echo ""
echo "📚 $POSTMAN_DIR/postman-collection-practice.json:"
echo "   • Learning-oriented version with TODO sections"
echo "   • Same structure as complete collection but empty tests"
echo "   • Perfect for hands-on API testing education"
echo ""
echo "🗄️  Database Management Commands:"
echo "=================================="
echo "• npm run db:seed       - Populate database with sample data"
echo "• npm run db:truncate   - Delete all data from database"
echo "• npm test              - Run test suite (requires clean/seeded DB)"
echo ""
echo "✨ Happy Testing!"
